### ISSUE TITLE
批量内购项目上传一直转圈

### ISSUE THREAD

**Issue by 18339689882** [37iOS/AppleParty#11]
**Describe the bug**
通过示例表格添加了5个内购商品，提交。

**To Reproduce**

**Expected behavior**
一直转圈。

**Screenshots**
<img width="204" alt="image" src="https://github.com/37MobileTeam/AppleParty/assets/39453295/520b01ef-8bcf-479e-8864-c80abbea78d5">

**Version** 
 - OS: Apple M2
 - AppleParty:  版本3.1.0 (2023.04.28)

**Comment by iHTCboy** [comment]
@18339689882  你好，在目录 `~/Documents/AppleParty/ASCAPI/` 下有日志文件，可以看看是什么原因导致啊
