### ISSUE TITLE
最近在重新更新充值项的标题和内容时会返回这个

### ISSUE THREAD

**Issue by 954708775** [37iOS/AppleParty#12]
Error code: ENTITY_ERROR.ATTRIBUTE.INVALID.UNMODIFIABLE, title: The provided entity contains a field that can not be modified in the current state, detail: Optional("Cannot edit InAppPurchaseLocalization when it is in ACTIVE state")

不确定是api接口出问题，还是bug

**Comment by 954708775** [comment]
我自己尝试过了，确认应该是api接口的问题了，看来需要开发新功能或者怎么完善下

**Comment by iHTCboy** [comment]
@954708775 你好，已经更改了，可以试试 3.2.0 是否可以啊
