### ISSUE TITLE
当前请求异常，请检查密钥是否正确。 -- 内购批处理上传的时候报了这个错误

### ISSUE THREAD

**Issue by pusswzy** [37iOS/AppleParty#16]
我能确认密钥是准确无误的

**Comment by pusswzy** [comment]
已经解决，重启VMWare后，重新登录了AppleParty，即可

**Comment by CocoaKier** [comment]
我也遇到这个问题了，确认密钥没有问题。重启、重新登陆AppleParty还是不行

**Comment by CocoaKier** [comment]
最终我发现是代码生成的token无效导致的，无效的原因未知。

我通过ruby脚本自己生成了token，再通过Charles抓包工具的Rewrite功能强行修改了，AppleParty这两个域名的的请求头参数
api.appstoreconnect.apple.com/v1/*
api.appstoreconnect.apple.com/v2/*

将 authorization 的值改为 自己生成的token值，完成了批量上传。

<img width="1187" alt="image" src="https://github.com/user-attachments/assets/6a4e3e49-90a5-42c1-889d-c854b44cf5cf">
