### ISSUE TITLE
3.7.0 登陆超时以及登陆后身份凭据无效

### ISSUE THREAD

**Issue by SakuraOwO-star** [37iOS/AppleParty#17]
问题1：3.7.0登陆是使用的授权登陆，但已经在浏览器打开appstoreconnect.apple.com并登录后，进行授权时会提示401超时。
问题2：登录后，打开我的App，提示“Authentication credentials are missing or invalid.”

**Comment by iHTCboy** [comment]
@SakuraOwO-star 授权登录时，web页面中不要点击“信任设备”，试试这样行不行。（另外，在设置页面点击清缓存试试，可能上一次的cookies有影响：
<img width="513" alt="image" src="https://github.com/user-attachments/assets/ccb3dede-ad18-4a69-b9c9-ef863f4f0bce">

**Comment by SakuraOwO-star** [comment]
好的，清除缓存和取消勾选信任设备后就可以正常使用了，十分感谢 @iHTCboy
