### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by 954708775** [37iOS/AppleParty#2]
感谢有这个小工具，很有用。但是有几个问题想请教：
1. 目前的App Store connect 经过更新后，已经没有办法批量提交应用内商品审核了，之前是可以进行复选框，都配置好后，可以一键勾选。关于这个，请问有没有好的方法或者 工具是否可以增加这部分功能呢？
2.配置应用内商品时，如果有多个本地化语言版本，格式是直接在后面增加吗？
3.我自己使用下来别的脚本如果是已经通过的应用内商品 进行修改 商店描述，新增语言，更改价格，接口是不对外开放的。这个工具我尝试了下，会提示上传成功，但是经核实，没有对已经通过审核的应用内商品 有任何更改

**Comment by WackyShady** [comment]
I'm sure that AppleParty cannot work today and when you launch the developer accout then shows up a blank menu which we cannot operate anything on it.

Maybe the Apple has changed the API so is there any new way to bulid new iaps?

**Comment by iHTCboy** [comment]
@954708775 @WackyShady 

Sure, Apple's API changes made it unusable, and now version v2.0.5 has been fixed and can now be updated.

**Comment by iHTCboy** [comment]
@954708775 

1、目前的App Store connect 经过更新后，已经没有办法批量提交应用内商品审核了，之前是可以进行复选框，都配置好后，可以一键勾选。关于这个，请问有没有好的方法或者工具是否可以增加这部分功能呢？
答：这块的流程，新 app 送审前，可以勾选全部的内购商品吧，如图：
![image](https://user-images.githubusercontent.com/11418363/178890975-899e1ff8-89fc-4807-a995-e56b522fa1c1.png)

2、配置应用内商品时，如果有多个本地化语言版本，格式是直接在后面增加吗？
答：目前版本暂不支持多语言的内购品项创建，后续我们会增加支持。

3、我自己使用下来别的脚本如果是已经通过的应用内商品 进行修改 商店描述，新增语言，更改价格，接口是不对外开放的。这个工具我尝试了下，会提示上传成功，但是经核实，没有对已经通过审核的应用内商品 有任何更改
答：已经通过审核的应用内商品，测试发现可以更新内容，但更新的内容需要重新提审。

**Comment by 954708775** [comment]
感谢回复。

1.第一点问题，的确是新应用初审可以这样操作，之后均不可以。
2 3&nbsp; 期待新功能的更新。

祝一切顺利。


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "37iOS/AppleParty"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Jul 14, 2022 11:42 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [37iOS/AppleParty] 几个小问题 (Issue #2)





 
@954708775
 
1、目前的App Store connect 经过更新后，已经没有办法批量提交应用内商品审核了，之前是可以进行复选框，都配置好后，可以一键勾选。关于这个，请问有没有好的方法或者工具是否可以增加这部分功能呢？
 答：这块的流程，新 app 送审前，可以勾选全部的内购商品吧，如图：
 
 
2、配置应用内商品时，如果有多个本地化语言版本，格式是直接在后面增加吗？
 答：目前版本暂不支持多语言的内购品项创建，后续我们会增加支持。
 
3、我自己使用下来别的脚本如果是已经通过的应用内商品 进行修改 商店描述，新增语言，更改价格，接口是不对外开放的。这个工具我尝试了下，会提示上传成功，但是经核实，没有对已经通过审核的应用内商品 有任何更改
 答：已经通过审核的应用内商品，测试发现可以更新内容，但更新的内容需要重新提审。

**Comment by 954708775** [comment]
补充一下，

这个新的问题，无论如何输入密码，只有点击拒绝才会停止弹出，点击其他两个按钮会持续弹出此对话框
如图所示

升级macOS 至 Monterey 12.4后仍然有这个问题。

祝一切顺利。


------------------ Original ------------------
From:                                                                                                                        "37iOS/AppleParty"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Jul 14, 2022 11:42 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [37iOS/AppleParty] 几个小问题 (Issue #2)





 
@954708775
 
1、目前的App Store connect 经过更新后，已经没有办法批量提交应用内商品审核了，之前是可以进行复选框，都配置好后，可以一键勾选。关于这个，请问有没有好的方法或者工具是否可以增加这部分功能呢？
 答：这块的流程，新 app 送审前，可以勾选全部的内购商品吧，如图：
 
 
2、配置应用内商品时，如果有多个本地化语言版本，格式是直接在后面增加吗？
 答：目前版本暂不支持多语言的内购品项创建，后续我们会增加支持。
 
3、我自己使用下来别的脚本如果是已经通过的应用内商品 进行修改 商店描述，新增语言，更改价格，接口是不对外开放的。这个工具我尝试了下，会提示上传成功，但是经核实，没有对已经通过审核的应用内商品 有任何更改
 答：已经通过审核的应用内商品，测试发现可以更新内容，但更新的内容需要重新提审。
