### ISSUE TITLE
苹果更新了价格等级

### ISSUE THREAD

**Issue by iOSleep** [37iOS/AppleParty#8]
**Describe the bug**
苹果更新了价格等级，现在获取不到价格了

**Version**
 - OS: 12.6.3
 - AppleParty:2.1.1

**Comment by MrIceCream** [comment]
同样的问题+1

**Comment by iHTCboy** [comment]
@iOSleep @MrIceCream 收到，这个月会研究，稍晚更新兼容啊~

**Comment by iHTCboy** [comment]
@iOSleep @MrIceCream AppleParty v3 已经支持 App Store 新定价机制和批量配置自定价格和销售范围。

使用教程文章链接：
https://juejin.cn/post/7226327556198744122
